# fly.toml app configuration file generated for messaging-microservice on 2023-10-11T15:39:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messaging-microservice"
primary_region = "sea"

[build]
  image = "scottkenning/messaging-image"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
