# fly.toml app configuration file generated for resident-management on 2023-10-14T15:19:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "resident-management"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
